### ISSUE TITLE
cant create migrations on windows cant find any answer anywhere online or even anyone who has had similar problem 

### ISSUE THREAD

**Issue by kinyodan** [railsware/activeresource-persistent#2]
all of a sudden out of nowhere i can run any migrations at all im stuck now can go on with making my app even tried moving from ruby 2.0.0 to 2.1.9 then 2.3.3 still same problem 

C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'active_resource/persistent'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Process::RLIMIT_NOFILE
Backtrace for gem load error is:
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:205:in `<class:Persistent>'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:190:in `<top (required)>'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/activeresource-persistent-0.2.0/lib/active_resource/persistent/http.rb:1:in `require'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/activeresource-persistent-0.2.0/lib/active_resource/persistent/http.rb:1:in `<top (required)>'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/activeresource-persistent-0.2.0/lib/active_resource/persistent.rb:1:in `require'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/activeresource-persistent-0.2.0/lib/active_resource/persistent.rb:1:in `<top (required)>'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
c:/PATCHED/beimarket/config/application.rb:10:in `<top (required)>'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:118:in `require'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:118:in `configurations'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:99:in `config'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:22:in `start'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:11:in `start'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:86:in `dbconsole'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
        from c:/PATCHED/beimarket/config/application.rb:10:in `<top (required)>'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:118:in `require'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:118:in `configurations'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:99:in `config'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:22:in `start'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/dbconsole.rb:11:in `start'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:86:in `dbconsole'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by ayanko** [comment]
@kinyodan  I don't think that this issue is due to this gem

```
There was an error while trying to load the gem 'active_resource/persistent'. (Bundler::GemRequireError) Gem Load Error is: uninitialized constant Process::RLIMIT_NOFILE Backtrace for gem load error is: c:/PATCHED/beimarket/.bundle/ruby/2.2.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:205:inclass:Persistent'
```

This is probably `net-http-persistent`.

Which version do you use? Try to add explicit version `2.8` to your Gemfile:

```ruby
gem 'net-http-persistent', '2.8' 
gem 'activeresource-persistent`
```

**Comment by ayanko** [comment]
@kinyodan  You need to improve your "googling" skills: 
https://github.com/drbrain/net-http-persistent/issues/79
